spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jmcdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true