spring:
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: update

  h2:
    console:
      path: /sql
      settings.trace: false
      settings.web-allow-others: false

server:
  port: 6140
  context-path: rest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    filter: true
    tagsSorter: alpha
    docExpansion: 'none'